require_relative '../timeline'

example_timeline = [
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :countdown,
    :countdown,
    :nothing,
    :countdown,
    :countdown,
    :nothing,
    :countdown,
    :countdown,
    :countdown,
    :countdown,
    :countdown,
    :nothing,
    :countdown,
    :countdown,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :ending,
    :ending,
    :ending,
    :ending,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    # Someone in orange armor ran in front of the screen
    :countdown,
    :nothing,
    :countdown,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :countdown,
    :countdown,
    :nothing,
    :countdown,
    :countdown,
    :countdown,
    :countdown,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :nothing,
    :ending,
    :ending,
    :nothing,
    :ending,
    :ending,
]

puts "actual partition: #{Timeline.new(example_timeline).partition}"

puts "expected partition: #{
[
    {start: 4-17, end: 22-25},
    {start: 46-52, end: 66-70}
]}"